/* The following code was generated by JFlex 1.4.3 on 12/20/14 2:23 PM */

package com.atsplugin;

import com.intellij.lexer.FlexLexer;
import com.intellij.psi.tree.IElementType;
import com.atsplugin.psi.ATSTypes;
import com.intellij.psi.TokenType;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 12/20/14 2:23 PM from the specification file
 * <tt>C:/cygwin64/home/brand_000/IntelliJATS/src/com/atslangplugin/ATS.flex</tt>
 */
class ATSLexer implements FlexLexer {
  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int STRING = 2;
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\0\1\1\1\0\1\4\1\2\22\0\1\4\1\14\1\0"+
    "\1\24\1\20\1\71\1\0\1\70\1\6\1\10\1\7\1\51\1\62"+
    "\1\25\1\21\1\5\1\11\11\12\1\16\1\63\1\17\1\22\1\23"+
    "\1\72\1\13\32\0\1\64\1\3\1\65\1\0\1\61\1\15\1\27"+
    "\1\30\1\50\1\44\1\35\1\54\1\47\1\56\1\41\1\0\1\57"+
    "\1\52\1\46\1\43\1\37\1\34\1\55\1\36\1\31\1\32\1\45"+
    "\1\40\1\42\1\53\1\33\1\60\1\66\1\0\1\67\1\26\uff81\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\1\1\0\1\2\1\3\1\2\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\2\1\20\21\2\1\21\1\22\1\23\1\24"+
    "\1\25\1\26\1\2\1\27\1\30\1\2\1\31\1\0"+
    "\1\32\1\33\1\34\1\35\1\36\1\37\13\0\2\40"+
    "\1\41\1\42\1\0\1\43\1\44\1\45\7\0\1\46"+
    "\1\47\1\50\1\0\1\51\23\0\1\52\1\0\1\53"+
    "\2\0\1\54\1\0\1\55\7\0\1\56\12\0\1\57"+
    "\1\0\1\60\1\61\1\62\1\63\1\4\1\0\3\31"+
    "\1\0\1\31\20\0\1\64\1\0\1\65\1\66\7\0"+
    "\1\67\2\0\1\70\2\0\1\71\1\0\1\72\4\0"+
    "\1\73\2\0\1\74\12\0\1\75\3\0\1\76\1\72"+
    "\2\0\1\77\1\100\14\0\1\101\1\102\5\0\1\103"+
    "\1\57\1\0\2\31\4\0\1\104\3\0\1\105\5\0"+
    "\1\106\1\107\1\110\32\0\1\111\1\112\7\0\1\113"+
    "\4\0\1\114\2\0\1\100\4\0\1\115\1\0\1\116"+
    "\7\0\1\117\1\0\1\101\2\0\1\120\1\0\1\103"+
    "\1\0\2\31\2\121\1\122\26\0\1\123\1\0\1\124"+
    "\3\0\1\125\1\126\12\0\1\127\1\130\7\0\1\131"+
    "\1\111\13\0\1\132\1\0\1\133\5\0\1\134\1\135"+
    "\10\0\1\117\1\0\1\136\1\137\1\140\1\0\1\31"+
    "\2\0\1\141\1\0\2\104\10\0\1\142\1\0\1\105"+
    "\2\0\1\143\4\0\1\106\2\0\1\144\1\145\1\146"+
    "\4\0\1\147\1\0\1\150\3\0\1\151\1\152\1\153"+
    "\1\154\6\0\1\133\1\155\1\156\1\157\4\0\1\160"+
    "\4\0\1\161\1\162\5\0\1\163\2\0\1\164\2\0"+
    "\1\165\1\166\1\167\4\0\1\105\5\0\1\170\3\0"+
    "\1\171\1\172\2\173\1\174\1\175\1\176\1\177\1\200"+
    "\1\201\1\0\1\202\12\0\1\203\7\0\1\204\1\205"+
    "\6\0\1\206\1\207\2\0\1\210\1\0\2\211\1\212"+
    "\2\213\1\214\1\0\1\215\1\0\1\216\1\217\4\0"+
    "\1\220\1\221\1\222\1\223\7\0\1\224\1\225\1\226"+
    "\1\227\4\0\1\230\2\0\1\224";

  private static int [] zzUnpackAction() {
    int [] result = new int[582];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\73\0\166\0\166\0\261\0\354\0\166\0\u0127"+
    "\0\166\0\u0162\0\u019d\0\u01d8\0\u0213\0\u024e\0\u0289\0\u02c4"+
    "\0\u02ff\0\u033a\0\166\0\u0375\0\u03b0\0\u03eb\0\u0426\0\u0461"+
    "\0\u049c\0\u04d7\0\u0512\0\u054d\0\u0588\0\u05c3\0\u05fe\0\u0639"+
    "\0\u0674\0\u06af\0\u06ea\0\u0725\0\u0760\0\166\0\166\0\166"+
    "\0\166\0\166\0\u079b\0\u07d6\0\166\0\u0811\0\u084c\0\u0887"+
    "\0\166\0\166\0\166\0\166\0\166\0\166\0\u08c2\0\u08fd"+
    "\0\u0938\0\u0973\0\u09ae\0\u09e9\0\u0a24\0\u0a5f\0\u0a9a\0\u0ad5"+
    "\0\u0b10\0\166\0\u0b4b\0\u0b86\0\u0bc1\0\u0bfc\0\u0c37\0\u0c72"+
    "\0\166\0\u0cad\0\u0ce8\0\u0d23\0\u0d5e\0\u0d99\0\u0dd4\0\u0e0f"+
    "\0\166\0\u0e4a\0\166\0\u0e85\0\u0ec0\0\u0efb\0\u0f36\0\u0f71"+
    "\0\u0fac\0\u0fe7\0\u1022\0\u105d\0\u1098\0\u10d3\0\u110e\0\u1149"+
    "\0\u1184\0\u11bf\0\u11fa\0\u1235\0\u1270\0\u12ab\0\u12e6\0\u1321"+
    "\0\166\0\u135c\0\166\0\u1397\0\u13d2\0\u140d\0\u1448\0\166"+
    "\0\u1483\0\u14be\0\u14f9\0\u1534\0\u156f\0\u15aa\0\u15e5\0\166"+
    "\0\u1620\0\u165b\0\u1696\0\u16d1\0\u170c\0\u1747\0\u1782\0\u17bd"+
    "\0\u17f8\0\u1833\0\u186e\0\u18a9\0\166\0\166\0\166\0\166"+
    "\0\166\0\u18e4\0\u191f\0\166\0\u195a\0\u1995\0\u19d0\0\u1a0b"+
    "\0\u1a46\0\u1a81\0\u1abc\0\u1af7\0\u1b32\0\u1b6d\0\u1ba8\0\u1be3"+
    "\0\u1c1e\0\u1c59\0\u1c94\0\u1ccf\0\u1d0a\0\u1d45\0\u1d80\0\166"+
    "\0\u1dbb\0\166\0\166\0\u1df6\0\u1e31\0\u1e6c\0\u1ea7\0\u1ee2"+
    "\0\u1f1d\0\u1f58\0\u1f93\0\u1fce\0\u2009\0\166\0\u2044\0\u207f"+
    "\0\166\0\u20ba\0\166\0\u20f5\0\u2130\0\u216b\0\u21a6\0\166"+
    "\0\u21e1\0\u221c\0\166\0\u2257\0\u2292\0\u22cd\0\u2308\0\u2343"+
    "\0\u237e\0\u23b9\0\u23f4\0\u242f\0\u246a\0\166\0\u24a5\0\u24e0"+
    "\0\u251b\0\166\0\u2556\0\u2591\0\u25cc\0\166\0\u2607\0\u2642"+
    "\0\u267d\0\u26b8\0\u26f3\0\u272e\0\u2769\0\u27a4\0\u27df\0\u281a"+
    "\0\u2855\0\u2890\0\u28cb\0\u2906\0\166\0\u2941\0\u297c\0\u29b7"+
    "\0\u29f2\0\u2a2d\0\u2a68\0\166\0\u2aa3\0\u2ade\0\u2b19\0\u2b54"+
    "\0\u2b8f\0\u2bca\0\u2c05\0\u2c40\0\u2c7b\0\u2cb6\0\u2cf1\0\u2d2c"+
    "\0\u2d67\0\u2da2\0\u2ddd\0\u2e18\0\u2e53\0\u2e8e\0\166\0\u2ec9"+
    "\0\u2f04\0\u2f3f\0\u2f7a\0\u2fb5\0\u2ff0\0\u302b\0\u3066\0\u30a1"+
    "\0\u30dc\0\u3117\0\u3152\0\u318d\0\u31c8\0\u3203\0\u323e\0\u3279"+
    "\0\u32b4\0\u32ef\0\u332a\0\u3365\0\u33a0\0\u33db\0\u3416\0\u3451"+
    "\0\u348c\0\u34c7\0\u3502\0\166\0\u353d\0\u3578\0\u35b3\0\u35ee"+
    "\0\u3629\0\u3664\0\u369f\0\166\0\u36da\0\u3715\0\u3750\0\u378b"+
    "\0\166\0\u37c6\0\u3801\0\166\0\u383c\0\u3877\0\u38b2\0\u38ed"+
    "\0\u3928\0\u3963\0\166\0\u399e\0\u39d9\0\u3a14\0\u3a4f\0\u3a8a"+
    "\0\u3ac5\0\u3b00\0\u3b3b\0\u3b76\0\166\0\u3bb1\0\u3bec\0\166"+
    "\0\u3c27\0\166\0\u3c62\0\u3c9d\0\u3cd8\0\u3d13\0\u3c9d\0\166"+
    "\0\u3d4e\0\u3d89\0\u3dc4\0\u3dff\0\u3e3a\0\u3e75\0\u3eb0\0\u3eeb"+
    "\0\u3f26\0\u3f61\0\u3f9c\0\u3fd7\0\u4012\0\u404d\0\u4088\0\u40c3"+
    "\0\u40fe\0\u4139\0\u4174\0\u41af\0\u41ea\0\u4225\0\166\0\u4260"+
    "\0\166\0\u429b\0\u42d6\0\u4311\0\166\0\u434c\0\u4387\0\u43c2"+
    "\0\u43fd\0\u4438\0\u4473\0\u44ae\0\u44e9\0\u4524\0\u455f\0\u459a"+
    "\0\166\0\166\0\u45d5\0\u4610\0\u464b\0\u4686\0\u46c1\0\u46fc"+
    "\0\u4737\0\166\0\166\0\u4772\0\u47ad\0\u47e8\0\u4823\0\u485e"+
    "\0\u4899\0\u48d4\0\u490f\0\u494a\0\u4985\0\u49c0\0\166\0\u49fb"+
    "\0\u4a36\0\u4a71\0\u4aac\0\u4ae7\0\u4b22\0\u4b5d\0\166\0\u4b98"+
    "\0\u4bd3\0\u4c0e\0\u4c49\0\u4c84\0\u4cbf\0\u4cfa\0\u4d35\0\u4d70"+
    "\0\166\0\u4dab\0\166\0\166\0\166\0\u4de6\0\u4e21\0\u4e5c"+
    "\0\u4e97\0\166\0\u4ed2\0\u4f0d\0\166\0\u4f48\0\u4f83\0\u4fbe"+
    "\0\u4ff9\0\u5034\0\u506f\0\u50aa\0\u50e5\0\166\0\u5120\0\166"+
    "\0\u515b\0\u5196\0\166\0\u51d1\0\u520c\0\u5247\0\u5282\0\166"+
    "\0\u52bd\0\u52f8\0\166\0\166\0\166\0\u5333\0\u536e\0\u53a9"+
    "\0\u53e4\0\166\0\u541f\0\166\0\u545a\0\u5495\0\u54d0\0\166"+
    "\0\166\0\166\0\166\0\u550b\0\u5546\0\u5581\0\u55bc\0\u55f7"+
    "\0\u5632\0\166\0\166\0\166\0\166\0\u566d\0\u56a8\0\u56e3"+
    "\0\u571e\0\166\0\u5759\0\u5794\0\u57cf\0\u580a\0\166\0\166"+
    "\0\u5845\0\u5880\0\u58bb\0\u58f6\0\u5931\0\166\0\u596c\0\u59a7"+
    "\0\166\0\u59e2\0\u5a1d\0\u5a58\0\166\0\166\0\u5a93\0\u5ace"+
    "\0\u5b09\0\u5b44\0\u5b7f\0\u5bba\0\u5bf5\0\u5c30\0\u5c6b\0\u5ca6"+
    "\0\166\0\u5ce1\0\u5d1c\0\u5d57\0\166\0\166\0\166\0\u5d92"+
    "\0\166\0\166\0\166\0\166\0\166\0\166\0\u5dcd\0\166"+
    "\0\u5e08\0\u5e43\0\u5e7e\0\u5eb9\0\u5ef4\0\u5f2f\0\u5f6a\0\u5fa5"+
    "\0\u5fe0\0\u601b\0\166\0\u6056\0\u5d92\0\u6091\0\u60cc\0\u6107"+
    "\0\u6142\0\u617d\0\166\0\166\0\u61b8\0\u61f3\0\u622e\0\u6269"+
    "\0\u62a4\0\u62df\0\166\0\166\0\u631a\0\u6355\0\166\0\u6390"+
    "\0\166\0\u63cb\0\166\0\166\0\u6406\0\166\0\u6441\0\166"+
    "\0\u647c\0\166\0\166\0\u64b7\0\u64f2\0\u652d\0\u6568\0\166"+
    "\0\166\0\166\0\166\0\u65a3\0\u65de\0\u6619\0\u6654\0\u668f"+
    "\0\u66ca\0\u6705\0\u6740\0\166\0\166\0\166\0\u677b\0\u67b6"+
    "\0\u67f1\0\u682c\0\166\0\u6867\0\u68a2\0\166";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[582];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\3\3\1\4\1\3\1\5\1\6\1\3\1\7\2\3"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\3\1\30\1\31\1\32\1\33\1\34\1\35\1\36"+
    "\1\37\1\40\1\3\1\41\1\3\1\42\1\3\1\43"+
    "\1\3\1\44\5\3\1\45\1\46\1\47\1\50\1\51"+
    "\1\52\1\53\1\54\1\55\27\3\1\56\43\3\100\0"+
    "\1\57\74\0\1\60\71\0\1\61\55\0\1\62\1\0"+
    "\1\63\12\0\1\64\103\0\1\65\76\0\1\66\76\0"+
    "\1\67\1\70\1\71\1\72\2\0\1\73\1\74\1\0"+
    "\1\75\3\0\1\76\1\0\1\77\1\0\1\100\1\0"+
    "\1\101\31\0\1\102\1\103\4\0\1\104\1\0\1\105"+
    "\56\0\1\106\11\0\1\107\3\0\1\110\70\0\1\111"+
    "\100\0\1\112\2\0\1\113\1\0\1\114\1\115\3\0"+
    "\1\116\2\0\1\117\1\120\16\0\1\121\25\0\1\122"+
    "\3\0\1\123\77\0\1\124\1\125\11\0\1\126\1\127"+
    "\5\0\1\130\55\0\1\131\67\0\1\132\1\133\3\0"+
    "\1\134\1\0\1\135\6\0\1\136\55\0\1\137\2\0"+
    "\1\140\17\0\1\141\1\142\51\0\1\143\1\144\76\0"+
    "\1\145\6\0\1\146\1\147\54\0\1\150\71\0\1\151"+
    "\3\0\1\152\13\0\1\153\45\0\1\154\11\0\1\155"+
    "\74\0\1\156\2\0\1\157\5\0\1\160\54\0\1\161"+
    "\2\0\1\162\14\0\1\163\46\0\1\164\4\0\1\165"+
    "\62\0\1\166\3\0\1\167\3\0\1\170\62\0\1\171"+
    "\72\0\1\172\22\0\1\173\47\0\1\174\5\0\1\175"+
    "\1\0\1\176\12\0\1\177\56\0\1\200\1\201\1\0"+
    "\1\202\1\0\1\203\1\0\1\204\33\0\1\205\72\0"+
    "\1\206\55\0\1\207\1\0\1\210\12\0\1\211\114\0"+
    "\1\212\42\0\1\213\1\214\1\215\1\216\1\0\1\217"+
    "\65\213\7\220\1\0\63\220\36\0\1\221\72\0\1\222"+
    "\112\0\1\223\61\0\1\224\100\0\1\225\1\226\45\0"+
    "\1\227\5\0\1\230\105\0\1\231\57\0\1\232\70\0"+
    "\1\233\76\0\1\234\64\0\1\235\7\0\1\236\2\0"+
    "\1\76\37\0\2\103\103\0\1\237\70\0\1\240\73\0"+
    "\1\241\73\0\1\242\72\0\1\243\100\0\1\244\117\0"+
    "\1\245\52\0\1\246\72\0\1\247\4\0\1\250\6\0"+
    "\1\251\63\0\1\252\10\0\1\253\53\0\1\254\100\0"+
    "\1\255\52\0\1\256\100\0\1\257\72\0\1\260\105\0"+
    "\1\261\72\0\1\262\100\0\1\263\67\0\1\264\52\0"+
    "\1\265\111\0\1\266\62\0\1\267\110\0\1\270\45\0"+
    "\1\271\77\0\1\272\71\0\1\273\74\0\1\274\76\0"+
    "\1\275\60\0\1\276\5\0\1\277\1\0\1\300\1\301"+
    "\1\302\6\0\1\303\3\0\1\304\47\0\1\305\105\0"+
    "\1\306\57\0\1\307\73\0\1\310\10\0\1\263\4\0"+
    "\1\311\72\0\1\312\3\0\1\313\1\314\52\0\1\315"+
    "\73\0\1\316\13\0\1\317\55\0\1\320\111\0\1\321"+
    "\52\0\1\322\70\0\1\263\72\0\1\323\75\0\1\324"+
    "\3\0\1\325\77\0\1\263\67\0\1\326\61\0\1\327"+
    "\103\0\1\330\77\0\1\331\53\0\1\332\70\0\1\333"+
    "\111\0\1\334\56\0\1\335\110\0\1\336\51\0\1\337"+
    "\100\0\1\340\73\0\1\341\13\0\1\342\73\0\1\343"+
    "\72\0\1\344\62\0\1\344\60\0\1\345\41\0\1\213"+
    "\1\214\1\215\1\216\1\0\66\213\1\0\1\214\71\0"+
    "\2\213\1\346\71\213\1\214\1\215\1\216\1\0\1\347"+
    "\65\213\7\220\1\350\63\220\36\0\1\351\71\0\1\352"+
    "\74\0\1\353\67\0\1\354\70\0\1\355\114\0\1\356"+
    "\57\0\1\357\101\0\1\360\61\0\1\361\105\0\1\362"+
    "\72\0\1\363\1\0\1\364\61\0\1\365\61\0\1\366"+
    "\71\0\1\235\62\0\1\367\74\0\1\370\100\0\1\371"+
    "\76\0\1\372\76\0\1\373\67\0\1\374\100\0\1\375"+
    "\57\0\1\376\7\0\1\377\101\0\1\u0100\65\0\1\u0101"+
    "\1\u0102\102\0\1\u0103\62\0\1\u0104\60\0\1\u0105\1\0"+
    "\1\u0106\3\0\1\u0107\77\0\1\u0108\63\0\1\u0109\75\0"+
    "\1\u010a\63\0\1\u010b\11\0\1\u010c\3\0\1\u010d\1\0"+
    "\1\u010e\55\0\1\u010f\3\0\1\u0110\63\0\1\u0111\71\0"+
    "\1\u0112\76\0\1\u0113\100\0\1\u0114\72\0\1\u0115\102\0"+
    "\1\u0116\73\0\1\u0117\52\0\1\u0118\65\0\1\u0119\111\0"+
    "\1\u011a\53\0\1\u011b\106\0\1\344\1\0\1\204\57\0"+
    "\1\277\75\0\1\u011c\70\0\1\u011d\1\0\1\u011e\2\0"+
    "\1\u011f\67\0\1\u0120\50\0\1\u0121\124\0\1\u0122\63\0"+
    "\1\u0123\61\0\1\u0124\23\0\1\u0124\63\0\1\u0125\71\0"+
    "\1\u0126\70\0\1\u0127\12\0\1\u0128\76\0\1\u0129\52\0"+
    "\1\u012a\4\0\1\u012b\101\0\1\u012c\74\0\1\u012d\45\0"+
    "\1\u012e\115\0\1\u012f\56\0\1\u0130\5\0\1\u0131\60\0"+
    "\1\u0132\2\0\1\u0133\66\0\1\u0134\54\0\1\u0135\106\0"+
    "\1\u0136\111\0\1\u0135\61\0\1\u0137\44\0\1\u0138\127\0"+
    "\1\u0139\41\0\1\u013a\117\0\1\u013b\32\0\2\213\1\215"+
    "\1\216\1\0\66\213\1\347\1\u013c\1\u013d\1\u013e\1\u013f"+
    "\66\347\7\220\1\350\1\u0140\62\220\34\0\1\u0141\65\0"+
    "\1\u0142\105\0\1\u0143\102\0\1\u0144\6\0\1\u0145\44\0"+
    "\1\u0146\1\0\1\u0147\2\0\1\u0148\5\0\1\u0149\5\0"+
    "\1\u014a\2\0\1\u014b\61\0\1\u014c\55\0\1\u014d\100\0"+
    "\1\u014e\21\0\1\u014f\45\0\1\u0150\65\0\1\u0151\102\0"+
    "\1\u0152\74\0\1\u0153\3\0\1\u0154\57\0\1\u0155\121\0"+
    "\1\u0156\34\0\1\u0157\104\0\1\u0158\100\0\1\u0159\72\0"+
    "\1\u015a\66\0\1\u015b\74\0\1\u015c\66\0\1\u015d\111\0"+
    "\1\u015e\70\0\1\u015f\64\0\1\u0160\63\0\1\u0161\76\0"+
    "\1\u0162\66\0\1\u0163\46\0\1\u0164\21\0\1\u0165\75\0"+
    "\1\u0166\66\0\1\u0105\6\0\1\u0167\77\0\1\u0168\37\0"+
    "\1\u0169\122\0\1\u016a\70\0\1\u016b\66\0\1\u016c\66\0"+
    "\1\u016d\100\0\1\u016e\105\0\1\u016f\63\0\1\u0170\73\0"+
    "\1\u0171\63\0\1\u0172\62\0\1\u0173\16\0\1\u0174\4\0"+
    "\1\u0173\65\0\1\u0175\67\0\1\344\72\0\1\u0176\75\0"+
    "\1\u0174\64\0\1\316\13\0\1\u0124\54\0\1\u0177\67\0"+
    "\1\u0178\75\0\1\u0179\74\0\1\u017a\63\0\1\u017b\77\0"+
    "\1\u017c\77\0\1\u017d\103\0\1\u017e\33\0\1\u017f\16\0"+
    "\1\u0180\11\0\1\u0174\101\0\1\u0181\55\0\1\u0182\71\0"+
    "\1\u0183\67\0\1\u0184\1\0\1\u0185\3\0\1\u0186\67\0"+
    "\1\u0187\72\0\1\u0188\76\0\1\u0189\62\0\1\u018a\1\u018b"+
    "\1\0\1\u018c\3\0\1\u018d\71\0\1\u018e\72\0\1\u018f"+
    "\70\0\1\u0190\111\0\1\204\43\0\1\u0191\23\0\1\u0191"+
    "\52\0\1\u0192\113\0\1\u0193\33\0\1\u0194\72\0\1\u0195"+
    "\111\0\1\u0105\6\0\1\u0196\31\0\74\u013f\1\u013c\71\u013f"+
    "\2\347\1\u0197\70\347\31\0\1\u0198\1\u0199\117\0\1\u019a"+
    "\45\0\1\u019b\75\0\1\u019c\67\0\1\u019d\5\0\1\u019e"+
    "\66\0\1\u019f\74\0\1\u01a0\63\0\1\u01a1\113\0\1\u01a2"+
    "\72\0\1\u01a3\63\0\1\u01a4\60\0\1\u01a5\100\0\1\u01a6"+
    "\73\0\1\u01a7\66\0\1\u01a8\5\0\1\u01a9\65\0\1\u01aa"+
    "\72\0\1\u01ab\107\0\1\u01ac\74\0\1\u01ad\63\0\1\u01ae"+
    "\70\0\1\u01af\63\0\1\u01b0\5\0\1\u01b1\70\0\1\u01b2"+
    "\66\0\1\u01b3\76\0\1\u01b4\110\0\1\u01b5\61\0\1\u01b6"+
    "\1\u01b7\73\0\1\u01b8\62\0\1\u01b9\111\0\1\u01ba\61\0"+
    "\1\u01bb\103\0\1\u01bc\51\0\1\u0165\73\0\1\u01bd\75\0"+
    "\1\u01be\70\0\1\u01bf\72\0\1\u01c0\105\0\1\u01c1\76\0"+
    "\1\u01c2\50\0\1\u01c3\67\0\1\u01c4\104\0\1\u01c5\63\0"+
    "\1\u01c6\75\0\1\u01c7\72\0\1\u01c8\72\0\1\u01c9\110\0"+
    "\1\u01ca\71\0\1\u0128\55\0\1\u0191\72\0\1\u01cb\100\0"+
    "\1\u01cc\65\0\1\u01cd\66\0\1\u01ce\76\0\1\u01cf\73\0"+
    "\1\u01d0\66\0\1\u01d1\75\0\1\u01ca\13\0\1\u01ca\52\0"+
    "\1\u01d2\106\0\1\u01d3\57\0\1\u01d4\75\0\1\u01d5\75\0"+
    "\1\u01d6\40\0\1\u01d7\136\0\1\u01d8\56\0\1\u01d9\66\0"+
    "\1\u01da\75\0\1\u01db\66\0\1\u018b\6\0\1\u01dc\60\0"+
    "\1\u01dd\107\0\1\u0131\102\0\1\u01de\62\0\1\u01df\63\0"+
    "\1\u01e0\35\0\2\347\1\u013d\1\u013e\1\u013f\66\347\60\0"+
    "\1\u01e1\50\0\1\u01e2\67\0\1\u01e3\120\0\1\u0145\43\0"+
    "\1\u019d\75\0\1\u01e4\100\0\1\u01e5\101\0\1\u01e6\47\0"+
    "\1\u01e7\72\0\1\u01e8\106\0\1\u01e9\60\0\1\u01ea\105\0"+
    "\1\u01eb\60\0\1\u01a8\75\0\1\u01ec\64\0\1\u01ed\100\0"+
    "\1\u01ee\105\0\1\u01ef\65\0\1\u01f0\61\0\1\u01b0\72\0"+
    "\1\u01f1\104\0\1\u01f2\63\0\1\u01f3\101\0\1\u01f4\102\0"+
    "\1\u01f5\53\0\1\u01f6\72\0\1\u01f7\71\0\1\u01f7\100\0"+
    "\1\u01f8\74\0\1\u01f9\74\0\1\u01fa\62\0\1\u01fb\110\0"+
    "\1\u01fc\72\0\1\u01fd\72\0\1\u01fe\57\0\1\u01ff\66\0"+
    "\1\u0200\64\0\1\u0201\77\0\1\u0202\73\0\1\u0203\71\0"+
    "\1\u0204\75\0\1\u0205\70\0\1\u0206\73\0\1\u0207\70\0"+
    "\1\u0208\75\0\1\u0209\70\0\1\u020a\101\0\1\u020b\63\0"+
    "\1\u020c\77\0\1\u020d\61\0\1\u020e\75\0\1\u020f\117\0"+
    "\1\u0210\63\0\1\u0211\72\0\1\u0212\64\0\1\u0213\105\0"+
    "\1\u0214\74\0\1\u014f\54\0\1\u0215\61\0\1\u0216\103\0"+
    "\1\u0217\61\0\1\u0218\105\0\1\u0219\62\0\1\u021a\111\0"+
    "\1\u021b\53\0\1\u021c\67\0\1\u021d\77\0\1\u021e\77\0"+
    "\1\u021f\63\0\1\u0118\100\0\1\u0220\64\0\1\u0221\71\0"+
    "\1\u0221\100\0\1\u0222\62\0\1\u0223\75\0\1\u0224\71\0"+
    "\1\u0224\100\0\1\u0225\100\0\1\u0226\63\0\1\u0227\66\0"+
    "\1\u0228\66\0\1\u0229\113\0\1\u022a\72\0\1\u022b\60\0"+
    "\1\u022c\73\0\1\u022d\60\0\1\u022e\104\0\1\u022f\66\0"+
    "\1\u0230\111\0\1\u0231\27\0\1\u0164\1\0\1\u0164\17\0"+
    "\1\u0165\102\0\1\u0232\61\0\1\u0233\72\0\1\u0184\72\0"+
    "\1\u018b\120\0\1\u0234\44\0\1\u0235\121\0\1\u0236\50\0"+
    "\1\u0237\101\0\1\u0238\63\0\1\u0239\70\0\1\u01e1\73\0"+
    "\1\u023a\74\0\1\u023b\75\0\1\u023c\64\0\1\u023d\100\0"+
    "\1\u023e\74\0\1\u023f\57\0\1\u0240\110\0\1\u0241\30\0"+
    "\1\u0242\116\0\1\u0243\100\0\1\u0244\64\0\1\u0245\50\0"+
    "\1\u0246\62\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[26845];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;
  private static final char[] EMPTY_BUFFER = new char[0];
  private static final int YYEOF = -1;
  private static java.io.Reader zzReader = null; // Fake

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\1\1\0\2\11\2\1\1\11\1\1\1\11\11\1"+
    "\1\11\22\1\5\11\2\1\1\11\2\1\1\0\6\11"+
    "\13\0\1\11\3\1\1\0\2\1\1\11\7\0\1\11"+
    "\1\1\1\11\1\0\1\1\23\0\1\11\1\0\1\11"+
    "\2\0\1\1\1\0\1\11\7\0\1\11\12\0\1\1"+
    "\1\0\5\11\1\0\1\1\1\11\1\1\1\0\1\1"+
    "\20\0\1\11\1\0\2\11\7\0\1\1\2\0\1\11"+
    "\2\0\1\11\1\0\1\11\4\0\1\11\2\0\1\11"+
    "\12\0\1\11\3\0\1\11\1\1\2\0\1\11\1\1"+
    "\14\0\1\1\1\11\5\0\1\1\1\11\1\0\2\1"+
    "\4\0\1\1\3\0\1\1\5\0\1\1\1\11\1\1"+
    "\32\0\1\1\1\11\7\0\1\11\4\0\1\11\2\0"+
    "\1\11\4\0\1\1\1\0\1\11\7\0\1\1\1\0"+
    "\1\11\2\0\1\11\1\0\1\11\1\0\4\1\1\11"+
    "\26\0\1\11\1\0\1\11\3\0\1\11\1\1\12\0"+
    "\2\11\7\0\2\11\13\0\1\11\1\0\1\1\5\0"+
    "\1\11\1\1\10\0\1\11\1\0\3\11\1\0\1\1"+
    "\2\0\1\11\1\0\1\1\1\11\10\0\1\11\1\0"+
    "\1\11\2\0\1\11\4\0\1\11\2\0\3\11\4\0"+
    "\1\11\1\0\1\11\3\0\4\11\6\0\4\11\4\0"+
    "\1\11\4\0\2\11\5\0\1\11\2\0\1\11\2\0"+
    "\1\1\2\11\4\0\1\1\5\0\1\11\3\0\3\11"+
    "\1\1\6\11\1\0\1\11\12\0\1\11\7\0\2\11"+
    "\6\0\2\11\2\0\1\11\1\0\1\11\1\1\2\11"+
    "\1\1\1\11\1\0\1\11\1\0\2\11\4\0\4\11"+
    "\7\0\1\1\3\11\4\0\1\11\2\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[582];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** this buffer may contains the current text array to be matched when it is cheap to acquire it */
  private char[] zzBufferArray;

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
  // Not sure if needed:
  StringBuffer string = new StringBuffer();


  ATSLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  ATSLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 140) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart(){
    return zzStartRead;
  }

  public final int getTokenEnd(){
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end,int initialState){
    zzBuffer = buffer;
    zzBufferArray = com.intellij.util.text.CharArrayUtil.fromSequenceWithoutCopying(buffer);
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzPushbackPos = 0;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBufferArray != null ? zzBufferArray[zzStartRead+pos]:zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElement advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;
    char[] zzBufferArrayL = zzBufferArray;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch ((zzBufferArrayL != null ? zzBufferArrayL[zzCurrentPosL] : zzBufferL.charAt(zzCurrentPosL))) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = (zzBufferArrayL != null ? zzBufferArrayL[zzMarkedPosL] : zzBufferL.charAt(zzMarkedPosL)) == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = (zzBufferArrayL != null ? zzBufferArrayL[zzMarkedPosL] : zzBufferL.charAt(zzMarkedPosL)) == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL)
            zzInput = (zzBufferArrayL != null ? zzBufferArrayL[zzCurrentPosL++] : zzBufferL.charAt(zzCurrentPosL++));
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = (zzBufferArrayL != null ? zzBufferArrayL[zzCurrentPosL++] : zzBufferL.charAt(zzCurrentPosL++));
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 113: 
          { return symbol(sym.WHILESTAR);
          }
        case 153: break;
        case 70: 
          { return symbol(sym.DLRLST);
          }
        case 154: break;
        case 43: 
          { return symbol(sym.OF);
          }
        case 155: break;
        case 101: 
          { return symbol(sym.SRPERROR);
          }
        case 156: break;
        case 67: 
          { return symbol(sym.FIX);
          }
        case 157: break;
        case 105: 
          { return symbol(sym.ASSUME);
          }
        case 158: break;
        case 100: 
          { return symbol(sym.SRPPRINT);
          }
        case 159: break;
        case 46: 
          { return symbol(sym.DO);
          }
        case 160: break;
        case 117: 
          { return symbol(sym.DLREXTYPE);
          }
        case 161: break;
        case 5: 
          { return symbol(sym.RPAREN);
          }
        case 162: break;
        case 150: 
          { return symbol(sym.DLRMYFILENAME);
          }
        case 163: break;
        case 37: 
          { return symbol(sym.GTDOT);
          }
        case 164: break;
        case 119: 
          { return symbol(sym.DLREXTVAL);
          }
        case 165: break;
        case 15: 
          { return symbol(sym.HASH);
          }
        case 166: break;
        case 36: 
          { return symbol(sym.EQGT);
          }
        case 167: break;
        case 87: 
          { return symbol(sym.ADDRAT);
          }
        case 168: break;
        case 38: 
          { return symbol(sym.HASHLBRACKETOLON);
          }
        case 169: break;
        case 128: 
          { return symbol(sym.TYPEDEF);
          }
        case 170: break;
        case 8: 
          { return symbol(sym.BQUOTE);
          }
        case 171: break;
        case 83: 
          { return symbol(sym.EQSLASHEQGTGT);
          }
        case 172: break;
        case 74: 
          { return symbol(sym.THEN);
          }
        case 173: break;
        case 24: 
          { return symbol(sym.QMARK);
          }
        case 174: break;
        case 18: 
          { return symbol(sym.SEMICOLON);
          }
        case 175: break;
        case 1: 
          { return symbol(sym.NONE);
          }
        case 176: break;
        case 14: 
          { return symbol(sym.GT);
          }
        case 177: break;
        case 90: 
          { return symbol(sym.VIEWAT);
          }
        case 178: break;
        case 126: 
          { return symbol(sym.SYMINTR);
          }
        case 179: break;
        case 152: 
          { return symbol(sym.DLREXTYPE_STRUCT);
          }
        case 180: break;
        case 35: 
          { return symbol(sym.EQLT);
          }
        case 181: break;
        case 132: 
          { return symbol(sym.DLREXTKIND);
          }
        case 182: break;
        case 40: 
          { return symbol(sym.MINUSGT);
          }
        case 183: break;
        case 149: 
          { return symbol(sym.DLRMYLOCATION);
          }
        case 184: break;
        case 95: 
          { return symbol(sym.FREEAT);
          }
        case 185: break;
        case 147: 
          { return symbol(sym.IMPLEMENT);
          }
        case 186: break;
        case 86: 
          { return symbol(sym.SRPELIF);
          }
        case 187: break;
        case 88: 
          { return symbol(sym.BEGIN);
          }
        case 188: break;
        case 65: 
          { return symbol(sym.LAM);
          }
        case 189: break;
        case 106: 
          { return symbol(sym.STATIC);
          }
        case 190: break;
        case 68: 
          { return symbol(sym.DLRTUP);
          }
        case 191: break;
        case 10: 
          { return symbol(sym.LT);
          }
        case 192: break;
        case 32: 
          { return symbol(sym.DOTINT);
          }
        case 193: break;
        case 93: 
          { return symbol(sym.WHILE);
          }
        case 194: break;
        case 13: 
          { return symbol(sym.EQ);
          }
        case 195: break;
        case 134: 
          { return symbol(sym.SRPELIFDEF);
          }
        case 196: break;
        case 120: 
          { return symbol(sym.SRPASSERT);
          }
        case 197: break;
        case 4: 
          { return symbol(sym.LPAREN);
          }
        case 198: break;
        case 39: 
          { return symbol(sym.MINUSLT);
          }
        case 199: break;
        case 20: 
          { return symbol(sym.RBRACKET);
          }
        case 200: break;
        case 84: 
          { return symbol(sym.SRPTHEN);
          }
        case 201: break;
        case 121: 
          { return symbol(sym.SRPIFNDEF);
          }
        case 202: break;
        case 73: 
          { return symbol(sym.TYPE);
          }
        case 203: break;
        case 135: 
          { return symbol(sym.SRPINCLUDE);
          }
        case 204: break;
        case 79: 
          { return symbol(sym.CASE);
          }
        case 205: break;
        case 96: 
          { return symbol(sym.FOLDAT);
          }
        case 206: break;
        case 107: 
          { return symbol(sym.STADEF);
          }
        case 207: break;
        case 140: 
          { return symbol(sym.CLASSDEC);
          }
        case 208: break;
        case 110: 
          { return symbol(sym.EXTERN);
          }
        case 209: break;
        case 129: 
          { return symbol(sym.TKINDEF);
          }
        case 210: break;
        case 25: 
          { return symbol(sym.COMMENT_line);
          }
        case 211: break;
        case 146: 
          { return symbol(sym.EXCEPTION);
          }
        case 212: break;
        case 41: 
          { return symbol(sym.AS);
          }
        case 213: break;
        case 81: 
          { return symbol(sym.COMMENT_rest);
          }
        case 214: break;
        case 76: 
          { return symbol(sym.REFAT);
          }
        case 215: break;
        case 58: 
          { return symbol(sym.DLREFFMASK_ARG);
          }
        case 216: break;
        case 133: 
          { return symbol(sym.DLREFFMASK);
          }
        case 217: break;
        case 51: 
          { return symbol(sym.QUOTELBRACE);
          }
        case 218: break;
        case 97: 
          { return symbol(sym.DLRBREAK);
          }
        case 219: break;
        case 114: 
          { return symbol(sym.NONFIX);
          }
        case 220: break;
        case 124: 
          { return symbol(sym.STALOAD);
          }
        case 221: break;
        case 130: 
          { return symbol(sym.REQUIRE);
          }
        case 222: break;
        case 62: 
          { return symbol(sym.REC);
          }
        case 223: break;
        case 54: 
          { return symbol(sym.EQGTGT);
          }
        case 224: break;
        case 104: 
          { return symbol(sym.SRPUNDEF);
          }
        case 225: break;
        case 115: 
          { return symbol(sym.MACDEF);
          }
        case 226: break;
        case 2: 
          { throw new Error("Illegal character <"+yytext()+">");
          }
        case 227: break;
        case 142: 
          { return symbol(sym.DLREXTMCALL);
          }
        case 228: break;
        case 66: 
          { return symbol(sym.LET);
          }
        case 229: break;
        case 28: 
          { return symbol(sym.ATLBRACE);
          }
        case 230: break;
        case 108: 
          { return symbol(sym.STACST);
          }
        case 231: break;
        case 11: 
          { return symbol(sym.DOLLAR);
          }
        case 232: break;
        case 60: 
          { return symbol(sym.TRY);
          }
        case 233: break;
        case 59: 
          { return symbol(sym.SIF);
          }
        case 234: break;
        case 118: 
          { return symbol(sym.DLREXTERN);
          }
        case 235: break;
        case 82: 
          { return symbol(sym.COMMENT_block);
          }
        case 236: break;
        case 98: 
          { return symbol(sym.DLRRAISE);
          }
        case 237: break;
        case 127: 
          { return symbol(sym.SORTDEF);
          }
        case 238: break;
        case 29: 
          { return symbol(sym.BQUOTELPAREN);
          }
        case 239: break;
        case 80: 
          { return symbol(sym.FORSTAR);
          }
        case 240: break;
        case 61: 
          { return symbol(sym.END);
          }
        case 241: break;
        case 17: 
          { return symbol(sym.COMMA);
          }
        case 242: break;
        case 139: 
          { return symbol(sym.DATATYPE);
          }
        case 243: break;
        case 148: 
          { return symbol(sym.DLRVCOPYENV);
          }
        case 244: break;
        case 44: 
          { return symbol(sym.IN);
          }
        case 245: break;
        case 33: 
          { return symbol(sym.DOTLT);
          }
        case 246: break;
        case 3: 
          { return symbol(sym.BACKSLASH);
          }
        case 247: break;
        case 136: 
          { return symbol(sym.OVERLOAD);
          }
        case 248: break;
        case 92: 
          { return symbol(sym.WHERE);
          }
        case 249: break;
        case 143: 
          { return symbol(sym.DLREXTFCALL);
          }
        case 250: break;
        case 103: 
          { return symbol(sym.SRPIFDEF);
          }
        case 251: break;
        case 9: 
          { return symbol(sym.COLON);
          }
        case 252: break;
        case 45: 
          { return symbol(sym.IF);
          }
        case 253: break;
        case 57: 
          { return symbol(sym.AND);
          }
        case 254: break;
        case 19: 
          { return symbol(sym.LBRACKET);
          }
        case 255: break;
        case 55: 
          { return symbol(sym.SRPIF);
          }
        case 256: break;
        case 47: 
          { return symbol(sym.FUN);
          }
        case 257: break;
        case 22: 
          { return symbol(sym.RBRACE);
          }
        case 258: break;
        case 123: 
          { return symbol(sym.ABSTYPE);
          }
        case 259: break;
        case 122: 
          { return symbol(sym.SRPDEFINE);
          }
        case 260: break;
        case 75: 
          { return symbol(sym.ELSE);
          }
        case 261: break;
        case 102: 
          { return symbol(sym.SRPENDIF);
          }
        case 262: break;
        case 151: 
          { return symbol(sym.DLRMYFUNCTION);
          }
        case 263: break;
        case 49: 
          { return symbol(sym.QUOTELPAREN);
          }
        case 264: break;
        case 72: 
          { return symbol(sym.EQSLASHEQGT);
          }
        case 265: break;
        case 89: 
          { return symbol(sym.SCASE);
          }
        case 266: break;
        case 23: 
          { return symbol(sym.PERCENT);
          }
        case 267: break;
        case 30: 
          { return symbol(sym.COLONLT);
          }
        case 268: break;
        case 71: 
          { return symbol(sym.DOTLTGTDOT);
          }
        case 269: break;
        case 131: 
          { return symbol(sym.DYNLOAD);
          }
        case 270: break;
        case 91: 
          { return symbol(sym.FIXITY);
          }
        case 271: break;
        case 53: 
          { return symbol(sym.EQLTGT);
          }
        case 272: break;
        case 145: 
          { return symbol(sym.SRPELIFNDEF);
          }
        case 273: break;
        case 144: 
          { return symbol(sym.DLRCONTINUE);
          }
        case 274: break;
        case 50: 
          { return symbol(sym.QUOTELBRACKET);
          }
        case 275: break;
        case 111: 
          { return symbol(sym.EXTVAR);
          }
        case 276: break;
        case 56: 
          { return symbol(sym.MINUSLTGT);
          }
        case 277: break;
        case 31: 
          { return symbol(sym.GTLT);
          }
        case 278: break;
        case 63: 
          { return symbol(sym.VAR);
          }
        case 279: break;
        case 6: 
          { return symbol(sym.AT);
          }
        case 280: break;
        case 109: 
          { return symbol(sym.EXTYPE);
          }
        case 281: break;
        case 125: 
          { return symbol(sym.SYMELIM);
          }
        case 282: break;
        case 34: 
          { return symbol(sym.DOTDOT);
          }
        case 283: break;
        case 85: 
          { return symbol(sym.SRPELSE);
          }
        case 284: break;
        case 64: 
          { return symbol(sym.VAL);
          }
        case 285: break;
        case 78: 
          { return symbol(sym.WHEN);
          }
        case 286: break;
        case 99: 
          { return symbol(sym.DLRDELAY);
          }
        case 287: break;
        case 42: 
          { return symbol(sym.OP);
          }
        case 288: break;
        case 77: 
          { return symbol(sym.WITH);
          }
        case 289: break;
        case 52: 
          { return symbol(sym.DOTDOTDOT);
          }
        case 290: break;
        case 69: 
          { return symbol(sym.DLRREC);
          }
        case 291: break;
        case 26: 
          { return symbol(sym.ATLPAREN);
          }
        case 292: break;
        case 21: 
          { return symbol(sym.LBRACE);
          }
        case 293: break;
        case 12: 
          { return symbol(sym.DOT);
          }
        case 294: break;
        case 112: 
          { return symbol(sym.IMPORT);
          }
        case 295: break;
        case 141: 
          { return symbol(sym.DLRSHOWTYPE);
          }
        case 296: break;
        case 7: 
          { return symbol(sym.BANG);
          }
        case 297: break;
        case 138: 
          { return symbol(sym.DATASORT);
          }
        case 298: break;
        case 27: 
          { return symbol(sym.ATLBRACKET);
          }
        case 299: break;
        case 16: 
          { return symbol(sym.TILDE);
          }
        case 300: break;
        case 137: 
          { return symbol(sym.WITHTYPE);
          }
        case 301: break;
        case 48: 
          { return symbol(sym.COMMALPAREN);
          }
        case 302: break;
        case 116: 
          { return symbol(sym.DLRARRPSZ);
          }
        case 303: break;
        case 94: 
          { return symbol(sym.LOCAL);
          }
        case 304: break;
        default:
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              {
                return symbol(sym.EOF);
              }
          }
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
