{
  parserClass="com.atslangplugin.parser.ATSParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="ATS"
  psiImplClassSuffix="Impl"
  psiPackage="com.atslangplugin.psi"
  psiImplPackage="com.atslangplugin.psi.impl"

  elementTypeHolderClass="com.atslangplugin.psi.ATSTypes"
  elementTypeClass="com.atslangplugin.psi.ATSElementType"
  tokenTypeClass="com.atslangplugin.psi.ATSTokenType"
}

ATSFile ::= item_*

private item_ ::= (property|COMMENT|CRLF)

property ::= (KEY? SEPARATOR VALUE?) | KEY

KEY ::=
NONE |
AT |
BACKSLASH |
BANG |
BQUOTE |
COLON |
COLONLT |
DOLLAR |
DOT |
DOTDOT |
DOTDOTDOT |
DOTINT |
EQ |
EQGT |
EQLT |
EQLTGT |
EQSLASHEQGT |
EQGTGT |
EQSLASHEQGTGT |
HASH |
LT |
GT |
GTLT |
DOTLT |
GTDOT |
DOTLTGTDOT |
MINUSGT |
MINUSLT |
MINUSLTGT |
TILDE |
ABSTYPE |
AND |
AS |
ASSUME |
BEGIN |
CASE |
CLASSDEC |
DATASORT |
DATATYPE |
DO |
DYNLOAD |
ELSE |
END |
EXCEPTION |
EXTERN |
EXTYPE |
EXTVAR |
FIX |
FIXITY |
FORSTAR |
FUN |
IF |
IMPLEMENT |
IMPORT |
IN |
LAM |
LET |
LOCAL |
MACDEF |
NONFIX |
OVERLOAD |
OF |
OP |
REC |
REFAT |
REQUIRE |
SCASE |
SIF |
SORTDEF |
STACST |
STADEF |
STALOAD |
STATIC |
SYMELIM |
SYMINTR |
THEN |
TKINDEF |
TRY |
TYPE |
TYPEDEF |
VAL |
VAR |
WHEN |
WHERE |
WHILE |
WHILESTAR |
WITH |
WITHTYPE |
ADDRAT |
FOLDAT |
FREEAT |
VIEWAT |
DLRARRPSZ |
DLRDELAY |
DLREFFMASK |
DLREFFMASK_ARG |
DLREXTERN |
DLREXTKIND |
DLREXTYPE |
DLREXTYPE_STRUCT |
DLREXTVAL |
DLREXTFCALL |
DLREXTMCALL |
DLRBREAK |
DLRCONTINUE |
DLRRAISE |
DLRLST |
DLRREC |
DLRTUP |
DLRMYFILENAME |
DLRMYLOCATION |
DLRMYFUNCTION |
DLRSHOWTYPE |
DLRVCOPYENV |
SRPASSERT |
SRPDEFINE |
SRPELIF |
SRPELIFDEF |
SRPELIFNDEF |
SRPELSE |
SRPENDIF |
SRPERROR |
SRPIF |
SRPIFDEF |
SRPIFNDEF |
SRPINCLUDE |
SRPPRINT |
SRPTHEN |
SRPUNDEF |
INT |
CHAR |
FLOAT |
CDATA |
STRING |
COMMA |
SEMICOLON |
LPAREN |
RPAREN |
LBRACKET |
RBRACKET |
LBRACE |
RBRACE |
ATLPAREN |
QUOTELPAREN |
ATLBRACKET |
QUOTELBRACKET |
HASHLBRACKETOLON |
ATLBRACE |
QUOTELBRACE |
BQUOTELPAREN |
COMMALPAREN |
PERCENTLPAREN |
EXTCODE |
COMMENT_LINE |
COMMENT_BLOCK |
COMMENT_REST |
PERCENT |
QMARK |
EOF |